# Generated by Django 5.2.11 on 2026-02-23 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cui', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('financial_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(blank=True, limit_choices_to={'role': 'analyst'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_companies', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='FinancialUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobat'), ('rejected', 'Respins')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_date', models.DateField(help_text='Data bilanțului (ex: ultima zi a lunii)')),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ebit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sales_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('short_term_liabilities', models.DecimalField(decimal_places=2, max_digits=15)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('retained_earnings', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='core.company')),
                ('source_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_statements', to='core.financialupload')),
            ],
            options={
                'verbose_name': 'Situație Financiară',
                'verbose_name_plural': 'Situații Financiare',
                'ordering': ['-reporting_date'],
                'unique_together': {('company', 'reporting_date')},
            },
        ),
    ]
