# Generated by Django 5.2.11 on 2026-02-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_financialupload_financialstatement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialstatement',
            options={'ordering': ['-reporting_date'], 'verbose_name': 'Financial Statement', 'verbose_name_plural': 'Financial Statements'},
        ),
    ]
