# Generated by Django 5.2.11 on 2026-02-23 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kpisnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Versiune Model ML',
            },
        ),
        migrations.AddField(
            model_name='financialupload',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialupload',
            name='processed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'analyst'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/standard/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_reports', to='core.kpisnapshot')),
            ],
            options={
                'verbose_name': 'Standard Report',
                'verbose_name_plural': 'Standard Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificare',
                'verbose_name_plural': 'Notificări',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_message', models.TextField(help_text='Ce dorește clientul să urmărească?', verbose_name='Mesaj/Cerințe Client')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('in_progress', 'În lucru'), ('completed', 'Finalizat')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(blank=True, limit_choices_to={'role': 'analyst'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_report_requests', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_requests', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst_message', models.TextField(help_text='Explicații trimise clientului odată cu raportul', verbose_name='Comentariu Analist')),
                ('expert_recommendations', models.TextField()),
                ('extra_data_json', models.JSONField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_report', to='core.reportrequest')),
            ],
        ),
    ]
