# Generated by Django 5.2.11 on 2026-02-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mlmodelversion_financialupload_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreport',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/custom/%Y/%m/'),
        ),
    ]
